"""LLM client protocol and OpenRouter client implementation."""

import asyncio
import json
import logging
import time
from typing import Any, Literal, Protocol, TypeVar

import httpx
from pydantic import BaseModel, ConfigDict, Field

from app.integrations.llm.exceptions import (
    LLMAuthError,
    LLMError,
    LLMMalformedOutputError,
    LLMRateLimitError,
    LLMTimeoutError,
)
from app.integrations.observability.tracer import get_current_tracer

logger = logging.getLogger(__name__)

TModel = TypeVar("TModel", bound=BaseModel)


class ToolCallRequest(BaseModel):
    """Normalized tool call emitted by an LLM."""

    model_config = ConfigDict(frozen=True)

    id: str = Field(..., description="Unique tool call identifier generated by the model")
    function_name: str = Field(..., description="Name of the function/tool to execute")
    arguments: dict[str, Any] = Field(
        default_factory=dict, description="Parsed arguments dictionary"
    )


class LLMMessage(BaseModel):
    """Standardized chat completion message."""

    model_config = ConfigDict(frozen=True)

    role: Literal["system", "user", "assistant", "tool"] = Field(..., description="Message role")
    content: str | None = Field(default=None, description="Text content of the message")
    tool_calls: list[ToolCallRequest] | None = Field(
        default=None, description="Tool calls issued by the assistant"
    )
    tool_call_id: str | None = Field(
        default=None, description="ID of the tool call this message is responding to"
    )


class LLMResponse(BaseModel):
    """Normalized model inference response."""

    model_config = ConfigDict(frozen=True)

    content: str | None = Field(default=None, description="Generated assistant text response")
    tool_calls: list[ToolCallRequest] = Field(
        default_factory=list, description="Tool calls requested by the model"
    )
    finish_reason: Literal["stop", "tool_calls", "length", "error"] = Field(
        default="stop", description="Model completion stop condition"
    )
    model_used: str = Field(..., description="Actual model that generated this completion")
    token_usage: dict[str, Any] | None = Field(
        default=None, description="Token usage accounting if available"
    )


class LLMClient(Protocol):
    """Protocol for LLM gateway inference clients."""

    async def complete(
        self,
        messages: list[LLMMessage],
        model: str,
        tools: list[dict[str, Any]] | None = None,
        tool_choice: str | dict[str, Any] | None = None,
        response_format: dict[str, Any] | None = None,
        temperature: float = 0.0,
        max_tokens: int | None = None,
        role: str | None = None,
    ) -> LLMResponse:
        """Execute a chat completion with optional tool definitions."""
        ...

    async def complete_structured(
        self,
        messages: list[LLMMessage],
        model: str,
        response_model: type[TModel],
        temperature: float = 0.0,
        max_tokens: int | None = None,
        role: str | None = None,
    ) -> TModel:
        """Execute chat completion and parse output into validated Pydantic model."""
        ...


class OpenRouterClient:
    """OpenRouter implementation of LLMClient protocol."""

    def __init__(
        self,
        api_key: str,
        base_url: str = "https://openrouter.ai/api/v1",
        timeout_seconds: float = 60.0,
        http_client: httpx.AsyncClient | None = None,
    ) -> None:
        self._api_key = api_key
        self._base_url = base_url.rstrip("/")
        self._timeout_seconds = timeout_seconds
        self._external_client = http_client
        self._semaphore = asyncio.Semaphore(1)

    def _get_headers(self) -> dict[str, str]:
        headers = {
            "Content-Type": "application/json",
            "HTTP-Referer": "https://pocket.app/discovery",
            "X-Title": "PMLytics-AI",
        }
        if self._api_key:
            headers["Authorization"] = f"Bearer {self._api_key}"
        return headers

    def _format_messages_payload(self, messages: list[LLMMessage]) -> list[dict[str, Any]]:
        formatted: list[dict[str, Any]] = []
        for m in messages:
            entry: dict[str, Any] = {"role": m.role}
            if m.content is not None:
                entry["content"] = m.content
            if m.tool_calls:
                entry["tool_calls"] = [
                    {
                        "id": tc.id,
                        "type": "function",
                        "function": {
                            "name": tc.function_name,
                            "arguments": json.dumps(tc.arguments),
                        },
                    }
                    for tc in m.tool_calls
                ]
            if m.tool_call_id:
                entry["tool_call_id"] = m.tool_call_id
            formatted.append(entry)
        return formatted

    async def complete(
        self,
        messages: list[LLMMessage],
        model: str,
        tools: list[dict[str, Any]] | None = None,
        tool_choice: str | dict[str, Any] | None = None,
        response_format: dict[str, Any] | None = None,
        temperature: float = 0.0,
        max_tokens: int | None = None,
        role: str | None = None,
    ) -> LLMResponse:
        """Execute chat completion through OpenRouter with evidence-based bounded token budget."""
        from app.config.settings import get_max_tokens_for_role

        resolved_max_tokens: int
        if max_tokens is not None:
            resolved_max_tokens = max_tokens
        elif role is not None:
            resolved_max_tokens = get_max_tokens_for_role(role)
        else:
            # Safe bounded fallback ceiling to prevent unconstrained 65,536-token reservations
            resolved_max_tokens = 2560

        payload: dict[str, Any] = {
            "model": model,
            "messages": self._format_messages_payload(messages),
            "temperature": temperature,
            "max_tokens": resolved_max_tokens,
            "stream": True,
            "stream_options": {"include_usage": True},
        }
        if tools:
            payload["tools"] = tools
            if tool_choice is not None:
                payload["tool_choice"] = tool_choice
        if response_format:
            payload["response_format"] = response_format

        url = f"{self._base_url}/chat/completions"
        headers = self._get_headers()

        tracer = get_current_tracer()
        llm_span = None
        if tracer and tracer.enabled:
            llm_span = tracer.start_span(
                name=f"llm:{model}",
                run_type="llm",
                inputs={
                    "messages": self._format_messages_payload(messages),
                    "model": model,
                    "role": role,
                    "max_tokens": resolved_max_tokens,
                    "temperature": temperature,
                },
                metadata={
                    "model": model,
                    "role": role,
                    "max_tokens": resolved_max_tokens,
                },
            )

        t_start = time.perf_counter()
        t_first_chunk: float | None = None
        content_parts: list[str] = []
        tool_calls_acc: dict[int, dict[str, Any]] = {}
        finish_reason_str: str = "stop"
        model_used: str = model
        provider_used: str | None = None
        usage_dict: dict[str, Any] | None = None

        max_retries = 3
        for attempt in range(1, max_retries + 1):
            content_parts.clear()
            tool_calls_acc.clear()
            t_first_chunk = None
            finish_reason_str = "stop"
            usage_dict = None

            client_to_use = self._external_client or httpx.AsyncClient(
                timeout=self._timeout_seconds
            )
            supports_stream = (self._external_client is None) or (
                getattr(self._external_client, "_supports_stream", False) is True
            )
            try:
                async with self._semaphore:
                    if supports_stream:
                        async with client_to_use.stream(
                            "POST", url, headers=headers, json=payload
                        ) as res:
                            if res.status_code in (401, 403):
                                raise LLMAuthError(
                                    f"OpenRouter authentication failed (status {res.status_code})"
                                )
                            if res.status_code == 429 or (
                                res.status_code == 402
                                and "in_flight_budget_exhausted"
                                in (await res.aread()).decode("utf-8", errors="ignore")
                            ):
                                if attempt < max_retries:
                                    retry_wait = 3.0 * attempt
                                    logger.warning(
                                        "Transient OpenRouter rate/in-flight limit (%d); waiting %.1fs (attempt %d/%d)...",
                                        res.status_code,
                                        retry_wait,
                                        attempt,
                                        max_retries,
                                    )
                                    await asyncio.sleep(retry_wait)
                                    continue
                                if res.status_code == 429:
                                    raise LLMRateLimitError("OpenRouter rate limit exceeded")
                                raise LLMError("OpenRouter in-flight budget exhausted (status 402)")
                            if res.status_code != 200:
                                err_body = (await res.aread()).decode("utf-8", errors="ignore")
                                raise LLMError(
                                    f"OpenRouter error (status {res.status_code}): {err_body[:500]}"
                                )

                            async for line in res.aiter_lines():
                                if not line.startswith("data: "):
                                    continue
                                data_str = line[6:].strip()
                                if data_str == "[DONE]":
                                    break
                                chunk = json.loads(data_str)
                                if "model" in chunk and chunk["model"]:
                                    model_used = str(chunk["model"])
                                if "provider" in chunk and chunk["provider"]:
                                    provider_used = str(chunk["provider"])
                                if "usage" in chunk and chunk["usage"]:
                                    usage_dict = chunk["usage"]

                                choices = chunk.get("choices", [])
                                if not choices:
                                    continue
                                choice = choices[0]
                                if choice.get("finish_reason"):
                                    finish_reason_str = choice["finish_reason"]

                                delta = choice.get("delta", {})
                                if t_first_chunk is None and (
                                    delta.get("content") or delta.get("tool_calls")
                                ):
                                    t_first_chunk = time.perf_counter()

                                if delta.get("content"):
                                    content_parts.append(delta["content"])

                                for tc_delta in delta.get("tool_calls", []):
                                    idx = tc_delta.get("index", 0)
                                    if idx not in tool_calls_acc:
                                        tool_calls_acc[idx] = {
                                            "id": tc_delta.get("id", ""),
                                            "name": tc_delta.get("function", {}).get("name", ""),
                                            "arguments": tc_delta.get("function", {}).get(
                                                "arguments", ""
                                            ),
                                        }
                                    else:
                                        if tc_delta.get("id"):
                                            tool_calls_acc[idx]["id"] = tc_delta["id"]
                                        if tc_delta.get("function", {}).get("name"):
                                            tool_calls_acc[idx]["name"] += tc_delta["function"][
                                                "name"
                                            ]
                                        if tc_delta.get("function", {}).get("arguments"):
                                            tool_calls_acc[idx]["arguments"] += tc_delta[
                                                "function"
                                            ]["arguments"]
                        break
                    else:
                        # Fallback for mock clients that only implement post
                        res = await client_to_use.post(url, headers=headers, json=payload)
                        if res.status_code in (401, 403):
                            raise LLMAuthError(
                                f"OpenRouter authentication failed (status {res.status_code})"
                            )
                        if res.status_code == 429 or (
                            res.status_code == 402 and "in_flight_budget_exhausted" in res.text
                        ):
                            if attempt < max_retries:
                                retry_wait = 3.0 * attempt
                                await asyncio.sleep(retry_wait)
                                continue
                            if res.status_code == 429:
                                raise LLMRateLimitError("OpenRouter rate limit exceeded")
                            raise LLMError(
                                f"OpenRouter in-flight budget exhausted: {res.text[:500]}"
                            )
                        if res.status_code != 200:
                            raise LLMError(
                                f"OpenRouter error (status {res.status_code}): {res.text[:500]}"
                            )
                        data = res.json()
                        t_first_chunk = time.perf_counter()
                        choice = data.get("choices", [{}])[0]
                        msg = choice.get("message", {})
                        if msg.get("content"):
                            content_parts.append(msg["content"])
                        finish_reason_str = choice.get("finish_reason", "stop")
                        model_used = str(data.get("model", model))
                        usage_dict = data.get("usage")
                        for raw_tc in msg.get("tool_calls", []):
                            func_meta = raw_tc.get("function", {})
                            raw_args = func_meta.get("arguments", "{}")
                            args_str = (
                                raw_args if isinstance(raw_args, str) else json.dumps(raw_args)
                            )
                            idx = len(tool_calls_acc)
                            tool_calls_acc[idx] = {
                                "id": raw_tc.get("id", f"call_{idx}"),
                                "name": func_meta.get("name", ""),
                                "arguments": args_str,
                            }
                        break
            except httpx.TimeoutException as exc:
                if attempt == max_retries:
                    logger.error("OpenRouter request timed out for model %s", model)
                    if tracer and llm_span:
                        tracer.end_span(llm_span, error=f"Request timed out: {exc}")
                    raise LLMTimeoutError(f"OpenRouter request timed out: {exc}") from exc
                await asyncio.sleep(2.0 * attempt)
                continue
            except (httpx.RequestError, httpx.RemoteProtocolError) as exc:
                if attempt == max_retries:
                    logger.error("OpenRouter connection/protocol failure: %s", exc)
                    if tracer and llm_span:
                        tracer.end_span(llm_span, error=f"Connection error: {exc}")
                    raise LLMError(f"OpenRouter connection error: {exc}") from exc
                await asyncio.sleep(2.0 * attempt)
                continue
            finally:
                if not self._external_client:
                    await client_to_use.aclose()

        t_end = time.perf_counter()
        total_latency_seconds = t_end - t_start
        ttft_seconds = (t_first_chunk - t_start) if t_first_chunk is not None else None

        finish_reason: Literal["stop", "tool_calls", "length", "error"]
        if finish_reason_str == "tool_calls":
            finish_reason = "tool_calls"
        elif finish_reason_str == "length":
            finish_reason = "length"
        elif finish_reason_str == "error":
            finish_reason = "error"
        else:
            finish_reason = "stop"

        prompt_tokens = 0
        completion_tokens = 0
        total_tokens = 0
        provider_reported_cost: float | None = None
        internally_estimated_cost: float | None = None
        usage_metadata: dict[str, Any] | None = None

        cached_tokens = 0
        cache_read_tokens = 0
        cache_write_tokens = 0

        if isinstance(usage_dict, dict):
            prompt_tokens = usage_dict.get("prompt_tokens") or usage_dict.get("input_tokens") or 0
            completion_tokens = (
                usage_dict.get("completion_tokens") or usage_dict.get("output_tokens") or 0
            )
            total_tokens = usage_dict.get("total_tokens") or (prompt_tokens + completion_tokens)

            # Extract provider-reported prompt cache metrics
            pt_details = usage_dict.get("prompt_tokens_details") or {}
            cached_tokens = pt_details.get("cached_tokens") or usage_dict.get("cached_tokens") or 0
            cache_read_tokens = usage_dict.get("cache_read_input_tokens") or cached_tokens
            cache_write_tokens = usage_dict.get("cache_creation_input_tokens") or 0

            if "cost" in usage_dict and usage_dict["cost"] is not None:
                try:
                    provider_reported_cost = float(usage_dict["cost"])
                except (TypeError, ValueError):
                    provider_reported_cost = None

            from app.integrations.llm.pricing import calculate_internal_cost

            internally_estimated_cost = calculate_internal_cost(
                model, prompt_tokens, completion_tokens
            )

            usage_metadata = {
                "input_tokens": prompt_tokens,
                "output_tokens": completion_tokens,
                "total_tokens": total_tokens,
            }
            if cached_tokens:
                usage_metadata["cached_tokens"] = cached_tokens
            if provider_reported_cost is not None:
                usage_metadata["total_cost"] = provider_reported_cost
            elif internally_estimated_cost is not None:
                usage_metadata["total_cost"] = internally_estimated_cost

        if not provider_used:
            if "openai" in model:
                provider_used = "OpenAI"
            elif "anthropic" in model:
                provider_used = "Anthropic"
            else:
                provider_used = "OpenRouter"

        llm_metadata = {
            "model": model,
            "model_used": model_used,
            "provider": provider_used,
            "role": role,
            "max_tokens": resolved_max_tokens,
            "input_tokens": prompt_tokens,
            "output_tokens": completion_tokens,
            "total_tokens": total_tokens,
            "cached_tokens": cached_tokens,
            "cache_read_tokens": cache_read_tokens,
            "cache_write_tokens": cache_write_tokens,
            "provider_reported_cost": provider_reported_cost,
            "internally_estimated_cost": internally_estimated_cost,
            "ttft_seconds": round(ttft_seconds, 4) if ttft_seconds is not None else None,
            "total_latency_seconds": round(total_latency_seconds, 4),
            "finish_reason": finish_reason,
        }

        if finish_reason == "length":
            logger.error(
                "Model completion truncated due to token budget ceiling: model=%s, max_tokens=%d",
                model,
                resolved_max_tokens,
            )
            if tracer and llm_span:
                tracer.end_span(
                    llm_span,
                    error=f"Model response was truncated: exceeded token budget ceiling of {resolved_max_tokens} tokens.",
                    usage_metadata=usage_metadata,
                    metadata=llm_metadata,
                )
            raise LLMMalformedOutputError(
                f"Model response was truncated: exceeded token budget ceiling of {resolved_max_tokens} tokens. "
                f"Silent truncation is prohibited."
            )

        parsed_tcs: list[ToolCallRequest] = []
        for idx in sorted(tool_calls_acc.keys()):
            tc_info = tool_calls_acc[idx]
            raw_args = tc_info["arguments"]
            try:
                args = json.loads(raw_args) if isinstance(raw_args, str) else raw_args
            except Exception:
                args = {}
            parsed_tcs.append(
                ToolCallRequest(
                    id=tc_info["id"] or f"call_{idx}",
                    function_name=tc_info["name"],
                    arguments=args,
                )
            )

        assembled_content = "".join(content_parts) if content_parts else None

        if tracer and llm_span:
            try:
                tracer.end_span(
                    llm_span,
                    outputs={
                        "content": assembled_content,
                        "tool_calls": [tc.model_dump() for tc in parsed_tcs]
                        if parsed_tcs
                        else None,
                        "finish_reason": finish_reason,
                    },
                    usage_metadata=usage_metadata,
                    metadata=llm_metadata,
                )
            except Exception as exc:
                logger.warning("Failed to record LLM span telemetry (fail-open): %s", exc)

        return LLMResponse(
            content=assembled_content,
            tool_calls=parsed_tcs,
            finish_reason=finish_reason,
            model_used=model_used,
            token_usage=usage_dict if isinstance(usage_dict, dict) else None,
        )

    async def complete_structured(
        self,
        messages: list[LLMMessage],
        model: str,
        response_model: type[TModel],
        temperature: float = 0.0,
        max_tokens: int | None = None,
        role: str | None = None,
    ) -> TModel:
        """Execute chat completion enforcing structured JSON output parsed into response_model."""
        system_schema_instruction = (
            f"\nYou must respond ONLY with a valid JSON object matching this schema:\n"
            f"{json.dumps(response_model.model_json_schema())}\n"
            f"Do not include code fences, preamble, or markdown formatting outside the JSON."
        )

        adjusted_messages = list(messages)
        if adjusted_messages and adjusted_messages[0].role == "system":
            first = adjusted_messages[0]
            adjusted_messages[0] = LLMMessage(
                role="system",
                content=(first.content or "") + "\n" + system_schema_instruction,
            )
        else:
            adjusted_messages.insert(
                0,
                LLMMessage(
                    role="system",
                    content="You are a helpful assistant." + system_schema_instruction,
                ),
            )

        response = await self.complete(
            messages=adjusted_messages,
            model=model,
            response_format={"type": "json_object"},
            temperature=temperature,
            max_tokens=max_tokens,
            role=role,
        )

        content = response.content or ""
        # Strip potential markdown code fences if model enclosed JSON
        cleaned = content.strip()
        if cleaned.startswith("```"):
            lines = cleaned.splitlines()
            if lines and lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].startswith("```"):
                lines = lines[:-1]
            cleaned = "\n".join(lines).strip()

        try:
            return response_model.model_validate_json(cleaned)
        except Exception as exc:
            # Fallback: find first '{' and use JSONDecoder().raw_decode to extract first complete JSON object
            start_idx = cleaned.find("{")
            if start_idx != -1:
                try:
                    dec = json.JSONDecoder()
                    obj, _ = dec.raw_decode(cleaned[start_idx:])
                    if response_model.__name__ == "EvidenceAssessment":
                        from app.orchestration.nodes.assessment_parser import (
                            safe_parse_assessment_payload,
                        )

                        return safe_parse_assessment_payload(obj)  # type: ignore[return-value]
                    return response_model.model_validate(obj)
                except Exception:
                    pass
            logger.error(
                "Failed to parse structured model output: %s. Content: %s", exc, content[:300]
            )
            raise LLMMalformedOutputError(
                f"Model response does not conform to schema {response_model.__name__}: {exc}"
            ) from exc
