/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recent investigations
         * @description Return durable investigation history for the authenticated user.
         */
        get: operations["list_investigations_api_v1_investigations_get"];
        put?: never;
        /**
         * Launch an asynchronous product investigation
         * @description Persist a new record, then launch its background investigation task.
         */
        post: operations["create_investigation_api_v1_investigations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve current lifecycle status and active agent
         * @description Retrieve progress state derived directly from the LangGraph investigation lifecycle.
         */
        get: operations["get_investigation_status_api_v1_investigations__investigation_id__get"];
        put?: never;
        post?: never;
        /** Delete a completed investigation and its durable workflow history */
        delete: operations["delete_investigation_api_v1_investigations__investigation_id__delete"];
        options?: never;
        head?: never;
        /** Rename an investigation in the owner's history */
        patch: operations["rename_investigation_api_v1_investigations__investigation_id__patch"];
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel an in-progress investigation
         * @description Explicitly cancel an active investigation task.
         */
        post: operations["cancel_investigation_api_v1_investigations__investigation_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry a failed investigation as a new run */
        post: operations["retry_investigation_api_v1_investigations__investigation_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume a checkpointed investigation after an ambiguous interruption */
        post: operations["recover_investigation_api_v1_investigations__investigation_id__recover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events (SSE) live progress stream
         * @description Stream live progress milestones with immediate initial snapshot and clean completion.
         */
        get: operations["stream_investigation_events_api_v1_investigations__investigation_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve full structured recommendation and evidence ledger
         * @description Retrieve completed investigation findings.
         *
         *     Returns HTTP 409 Conflict if the investigation is still actively executing.
         *     Returns HTTP 500 if execution failed. Never returns 200 for execution failures.
         */
        get: operations["get_investigation_result_api_v1_investigations__investigation_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sanitized system health and dependency readiness
         * @description Return health status without leaking secrets, API keys, or project tokens.
         */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CriticReviewSchema
         * @description Outcome of adversarial review and revision tracking.
         */
        CriticReviewSchema: {
            /**
             * Status
             * @enum {string}
             */
            status: "PASS" | "REVISE";
            /** Revisions Completed */
            revisions_completed: number;
            /** Critique Summary */
            critique_summary: string;
            /** Issues Addressed */
            issues_addressed?: string[];
        };
        /**
         * EvidenceLedgerItemSchema
         * @description Attributable evidence item from the authoritative ledger, scrubbed of credentials and raw payloads.
         */
        EvidenceLedgerItemSchema: {
            /** Ledger Entry Id */
            ledger_entry_id: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "zendesk" | "posthog" | "jira";
            /** Source Reference */
            source_reference: string;
            /** Finding */
            finding: string;
            /** Support Excerpt */
            support_excerpt: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Supporting Records */
            supporting_records?: components["schemas"]["EvidenceSupportingRecordSchema"][];
        };
        /**
         * EvidenceSupportingRecordSchema
         * @description Sanitized source record supporting an evidence summary.
         */
        EvidenceSupportingRecordSchema: {
            /** Record Id */
            record_id: string;
            /**
             * Record Type
             * @enum {string}
             */
            record_type: "ticket" | "comment" | "issue" | "metric";
            /** Source Reference */
            source_reference: string;
            /** Title */
            title: string;
            /** Excerpt */
            excerpt: string;
            /** Status */
            status?: string | null;
            /** Occurred At */
            occurred_at?: string | null;
            /** Attributes */
            attributes?: {
                [key: string]: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Sanitized system health status.
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Process
             * @default healthy
             */
            process: string;
            /** Investigation Service Initialized */
            investigation_service_initialized: boolean;
            /** Active Investigations Count */
            active_investigations_count: number;
            /** Dependencies */
            dependencies: {
                [key: string]: boolean;
            };
        };
        /**
         * InvestigationCreateRequest
         * @description Payload for launching a new product investigation.
         */
        InvestigationCreateRequest: {
            /**
             * User Query
             * @description The product question to investigate. Must be non-empty after trimming.
             */
            user_query: string;
            /**
             * Context
             * @description Optional additional context for the investigation.
             */
            context?: {
                [key: string]: unknown;
            };
            /** @description Optional PM-selected primary and comparison time windows. */
            scope?: components["schemas"]["InvestigationScope"];
        };
        /**
         * InvestigationDetailResponse
         * @description Complete synthesized investigation result with evidence ledger and telemetry.
         */
        InvestigationDetailResponse: {
            /** Investigation Id */
            investigation_id: string;
            /** User Query */
            user_query: string;
            /** Status */
            status: string;
            /** Duration Seconds */
            duration_seconds: number;
            scope?: components["schemas"]["InvestigationScope"];
            recommendation: components["schemas"]["ProductRecommendationSchema"];
            /** Evidence Ledger */
            evidence_ledger: {
                [key: string]: components["schemas"]["EvidenceLedgerItemSchema"];
            };
            critic_review: components["schemas"]["CriticReviewSchema"];
            telemetry_summary: components["schemas"]["TelemetrySummarySchema"];
        };
        /**
         * InvestigationRenameRequest
         * @description User-managed label for investigation history.
         */
        InvestigationRenameRequest: {
            /** Display Name */
            display_name: string;
        };
        /**
         * InvestigationScope
         * @description A bounded analysis window, with an optional comparison period.
         *
         *     A missing scope preserves the existing all-available-data behaviour.  When a
         *     window is supplied, it is carried through planning and specialist tasks so
         *     agents can state and respect the PM's period of interest.
         */
        InvestigationScope: {
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Comparison Start Time */
            comparison_start_time?: string | null;
            /** Comparison End Time */
            comparison_end_time?: string | null;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
        };
        /**
         * InvestigationStatusResponse
         * @description Lightweight lifecycle progress summary for an investigation.
         */
        InvestigationStatusResponse: {
            /** Investigation Id */
            investigation_id: string;
            /** User Query */
            user_query: string;
            /** Display Name */
            display_name?: string | null;
            /** Status */
            status: string;
            /** Current Stage */
            current_stage: string;
            /** Active Agent */
            active_agent: string | null;
            /** Revision Count */
            revision_count: number;
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Error */
            error?: string | null;
            scope?: components["schemas"]["InvestigationScope"];
        };
        /**
         * InvestigationSummaryResponse
         * @description Initial acceptance response for an asynchronous investigation.
         */
        InvestigationSummaryResponse: {
            /** Investigation Id */
            investigation_id: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Status Url */
            status_url: string;
            /** Events Url */
            events_url: string;
            /** Result Url */
            result_url: string;
        };
        /**
         * ProductRecommendationSchema
         * @description Full typed synthesis produced by PM and reviewed by Critic.
         */
        ProductRecommendationSchema: {
            /** Problem Statement */
            problem_statement: string;
            /** Why It Matters */
            why_it_matters: string;
            /** Affected Users */
            affected_users: string;
            /** Factual Observations */
            factual_observations: components["schemas"]["StructuredFindingSchema"][];
            /** Inferences */
            inferences: components["schemas"]["StructuredFindingSchema"][];
            /** Hypotheses */
            hypotheses: components["schemas"]["StructuredFindingSchema"][];
            /** Recommendation */
            recommendation: string;
            /** Recommendation Type */
            recommendation_type: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Success Metrics */
            success_metrics: string[];
            /** Risks */
            risks: string[];
            /** Likely Causes */
            likely_causes?: string[];
            /** Conflicting Evidence */
            conflicting_evidence?: string[];
            /** Disclosed Limitations */
            disclosed_limitations?: string[];
            /** Evidence Citations */
            evidence_citations?: components["schemas"]["StructuredEvidenceCitationSchema"][];
        };
        /**
         * StructuredEvidenceCitationSchema
         * @description Direct citation embedded in the final recommendation.
         */
        StructuredEvidenceCitationSchema: {
            /** Ledger Entry Id */
            ledger_entry_id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "zendesk" | "posthog" | "jira";
            /** Source Reference */
            source_reference: string;
            /** Finding */
            finding: string;
            /** Support */
            support: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
        };
        /**
         * StructuredFindingSchema
         * @description An individual finding explicitly categorized by epistemic type.
         */
        StructuredFindingSchema: {
            /** Statement */
            statement: string;
            /**
             * Epistemic Type
             * @enum {string}
             */
            epistemic_type: "fact" | "inference" | "hypothesis";
            /**
             * Evidence Ids
             * @description Authoritative ledger entry IDs directly supporting this statement.
             */
            evidence_ids?: string[];
        };
        /**
         * TelemetrySummarySchema
         * @description Sanitized telemetry summary capturing token usage and provider cost without leaking secrets.
         */
        TelemetrySummarySchema: {
            /** Investigation Id */
            investigation_id: string;
            /** Trace Id */
            trace_id?: string | null;
            /**
             * Llm Calls
             * @default 0
             */
            llm_calls: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /** Provider Reported Cost */
            provider_reported_cost?: number | null;
            /** Internally Estimated Cost */
            internally_estimated_cost?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_investigations_api_v1_investigations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationStatusResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_investigation_api_v1_investigations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investigation_status_api_v1_investigations__investigation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_investigation_api_v1_investigations__investigation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_investigation_api_v1_investigations__investigation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_investigation_api_v1_investigations__investigation_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_investigation_api_v1_investigations__investigation_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recover_investigation_api_v1_investigations__investigation_id__recover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_investigation_events_api_v1_investigations__investigation_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investigation_result_api_v1_investigations__investigation_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
